### ISSUE TITLE
getElementById

### ISSUE THREAD

**Issue by spencerthayer** [codebox/js-planet-phase#1]
drawPlanetPhase(document.getElementById('container'), 0.15, true);

<div id="container"></div>

This doesn't seem to work. Only document.body. Any idea why?

**Comment by codebox** [comment]
That code works ok for me, have you tried debugging to see what the problem is? Do you get any errors?

**Comment by spencerthayer** [comment]
I attempted to debug it but every value I sent to console.log didn't return anything useful. I am not sure why it wasn't working. It's okay I built and alternative solution.

**Comment by spencerthayer** [comment]
I attempted to debug it but every value I sent to console.log didn't return anything useful. I am not sure why it wasn't working. It's okay I built and alternative solution. However I may test the DIV issue a little more, though I recommend you check it out it as well.

**Comment by spencerthayer** [comment]
I attempted to debug it but every value I sent to console.log didn't return anything useful. I am not sure why it wasn't working. It's okay I built and alternative solution. However I may test the DIV issue a little more, though I recommend you check it out it as well.
