### ISSUE TITLE
Creates Infinite DIV files

### ISSUE THREAD

**Issue by spencerthayer** [codebox/js-planet-phase#2]
If one is updating the moon drawing function frequently (in this case as the moon moves across the sky) js-planet-phase draws a new DIV file for each instance. This quickly fills up the browsers memory.

**Comment by codebox** [comment]
Fair point, maybe I could add a new config value to allow the calling code to create and pass in its own DIV, then you could re-use the same one each time

**Comment by spencerthayer** [comment]
I attempted this but the existing code base for my project was making the creation and deletion of the moon a mess. The main problem with the infinite DIVs is that that crashes my clock application after 7 hours of use on an iPod and 12 on an iPhone ( I assume memory differences ).

I just built my own solution using SunCalc.net moon calculated values. Its an easily containable DIV using CSS so I can put the moon into the correct position in the sky without much code. http://codepen.io/spencerthayer/full/EjobVd/

**Comment by spencerthayer** [comment]
.
